---
THEME: minima
TITLE: Your awesome title
DESCRIPTION: Write an awesome description for your new site here. You can edit
  this text in config.yml. It will appear in your document head meta (for 
  Google search results) and in your feed.xml site description.
POSTS_PER_PAGE: 5
HEADER_PAGES:
- name: about
  title: About
- name: foo/bar
  title: FOOBAR
AUTHOR:
  name: Foo Bar
  email: name@domain.com
SOCIAL_LINKS:
  twitter: username
  github: username
GOOGLE_ANALYTICS: ~
DISQUS_SHORTNAME: ~